services:
  api-web:
    container_name: api-web
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - 4000:8080
      - 5005:5005
    depends_on:
      - api-db
    networks:
      - jr_backend
    volumes:
      - ../:/app
  api-db:
    container_name: api-db
    platform: linux/amd64
    image: mysql:8.4.2
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - ./conf:/etc/mysql/conf.d
    ports:
      - 3306:3306
    networks:
      - jr_backend

networks:
  jr_backend:

